[project]
name = "chit-fund-analyzer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jupyterlab>=4.5.0",
    "matplotlib>=3.10.7",
    "numpy>=2.3.5",
    "numpy-financial>=1.0.0",
    "pandas>=2.3.3",
    "plotly>=6.5.0",
]
